version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/apps/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/deployments/aio/community"
    schedule:
      interval: "weekly"
