# Generated by Django 6.0.7 on 2026-08-01 15:57

import plane.db.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='timezone',
            field=models.CharField(choices=plane.db.models.base.timezone_choices, default='UTC', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='timezone',
            field=models.CharField(choices=plane.db.models.base.timezone_choices, default='UTC', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_timezone',
            field=models.CharField(choices=plane.db.models.base.timezone_choices, default='UTC', max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='timezone',
            field=models.CharField(choices=plane.db.models.base.timezone_choices, default='UTC', max_length=255),
        ),
    ]
