FROM python:3.14.4-alpine

COPY --from=ghcr.io/astral-sh/uv:0.12.1 /uv /uvx /bin/

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 
ENV INSTANCE_CHANGELOG_URL=https://sites.plane.so/pages/691ef037bcfe416a902e48cb55f59891/

# Update system packages for security
RUN apk update && apk upgrade

WORKDIR /code

RUN apk add --no-cache --upgrade \
    "libpq" \
    "libxslt" \
    "xmlsec" \
    "ca-certificates" \
    "openssl"

COPY pyproject.toml uv.lock ./
RUN apk add --no-cache libffi-dev
RUN apk add --no-cache --virtual .build-deps \
    "bash~=5.3" \
    "g++" \
    "gcc" \
    "cargo" \
    "git" \
    "make" \
    "postgresql-dev" \
    "libc-dev" \
    "linux-headers" \
    && \
    uv export --frozen --no-default-groups --no-emit-project --output-file /tmp/plane-api.lock \
    && \
    uv pip install --system --strict --compile-bytecode --no-cache --requirements /tmp/plane-api.lock \
    && \
    rm /tmp/plane-api.lock \
    && \
    apk del .build-deps \
    && \
    rm -rf /var/cache/apk/*


# Add in Django deps and generate Django's static files
COPY manage.py manage.py
COPY plane plane/
COPY templates templates/
COPY package.json package.json

RUN apk --no-cache add "bash~=5.3"
COPY ./bin ./bin/

RUN mkdir -p /code/plane/logs
RUN chmod +x ./bin/*
RUN chmod -R 777 /code

# Expose container port and run entry point script
EXPOSE 8000

CMD ["./bin/docker-entrypoint-api.sh"]